version: "2.0"
volumes:
  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./mongo/data
  postgresql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./postgresql/data
  mysql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./mysql/data
services:
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    environment:
      - MONGO_INITDB_DATABASE=home-automation
  postgresql:
    image: postgres:12
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: home-automation
      POSTGRES_USER: home-automation
      POSTGRES_DB: home-automation
      PGDATA: /var/lib/postgresql/data/db-files/
    ports:
      - 5432:5432
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: home-automation
      MYSQL_PASSWORD: home-automation
      MYSQL_DATABASE: home-automation
  memcached:
    image: memcached:1.6.17
    ports:
        - "11211:11211"
    command: ["memcached"]
  device-management-service:
    build:
      context: ../services/device-management-service
      dockerfile: ./Dockerfile
    ports:
    - "5001:5000"
    environment:
      POSTGRES_DSN: postgresql://home-automation:home-automation@postgresql:5432/home-automation
    depends_on:
      - postgresql
  user-service:
    build:
      context: ../services/user-service
      dockerfile: ./Dockerfile
    ports:
    - "5002:5000"
    environment:
      POSTGRES_DSN: postgresql+asyncpg://home-automation:home-automation@postgresql:5432/home-automation
    depends_on:
      - postgresql